export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/orders";
export * from "@/pages/dashboard/authors";
export * from "@/pages/dashboard/books";
export * from "@/pages/dashboard/genres";
export * from "@/pages/dashboard/coupons";
export * from "@/pages/dashboard/users";
export * from "@/pages/dashboard/shippings";
export * from "@/pages/dashboard/shippings";
